language: php
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

matrix:
    include:
        - php: '5.3'
          dist: precise
        - php: '5.4'
          dist: precise
        - php: '5.5'
          dist: precise
        - php: '5.6'
        - php: '7.0'
        - php: '7.1'
        - php: '7.2'
        - php: '7.3'
        - php: '7.4'

script:
  - ./vendor/bin/phpunit -c tests/ --coverage-text